workflows:
  android-debug:
    name: Android Debug APK
    max_build_duration: 60
    environment:
      vars:
        JAVA_VERSION: 17
      node: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
